---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
    groups:
      gomod:
        update-types:
          - "patch"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
    groups:
      actions:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: docker
    directory: /deploy
    cooldown:
      default-days: 3
    schedule:
      interval: daily
